#!/usr/bin/env python3
"""Build serial NERDSS and run a tiny isolated smoke simulation."""

from __future__ import annotations

import argparse
import json
import platform
import shutil
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Iterable, List, Optional


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SEED = 123

SMOKE_INPUT = """# Minimal serial smoke test generated by tools/run_smoke_tests.py

start parameters
    nItr = 10
    timeStep = 0.1
    timeWrite = 5
    trajWrite = 5
    restartWrite = 5
    pdbWrite = 5
    transitionWrite = 5
    fromRestart = false
    overlapSepLimit = 2.3
    scaleMaxDisplace = 30.0
end parameters

start boundaries
    WaterBox = [100, 100, 100]
    implicitLipid = false
    xBCtype = reflect
    yBCtype = reflect
    zBCtype = reflect
end boundaries

start molecules
    A:1
end molecules

start reactions
end reactions
"""

SMOKE_MOL = """##
# Minimal molecule for the serial smoke test.
##

Name = A

D = [1.0, 1.0, 1.0]
Dr = [0.0, 0.0, 0.0]

COM 0.0000 0.0000 0.0000
a   0.0000 0.0000 0.0000

bonds = 1
COM a
"""


@dataclass
class CommandResult:
    command: List[str]
    cwd: str
    exit_code: Optional[int]
    runtime_seconds: float
    stdout: str
    stderr: str
    timed_out: bool = False

    @property
    def ok(self) -> bool:
        return self.exit_code == 0 and not self.timed_out

    def to_dict(self) -> Dict[str, object]:
        return {
            "command": self.command,
            "cwd": self.cwd,
            "exit_code": self.exit_code,
            "runtime_seconds": round(self.runtime_seconds, 6),
            "stdout": self.stdout,
            "stderr": self.stderr,
            "timed_out": self.timed_out,
        }


@dataclass
class SmokeReport:
    status: str = "failed"
    message: str = ""
    repo_root: str = str(REPO_ROOT)
    build_system: str = "make"
    executable: Optional[str] = None
    smoke_dir: Optional[str] = None
    artifact_dir: Optional[str] = None
    dependency_checks: Dict[str, object] = field(default_factory=dict)
    environment: Dict[str, str] = field(default_factory=dict)
    build: Optional[CommandResult] = None
    run: Optional[CommandResult] = None
    produced_files: List[Dict[str, object]] = field(default_factory=list)

    def to_dict(self) -> Dict[str, object]:
        return {
            "status": self.status,
            "message": self.message,
            "repo_root": self.repo_root,
            "build_system": self.build_system,
            "executable": self.executable,
            "smoke_dir": self.smoke_dir,
            "artifact_dir": self.artifact_dir,
            "dependency_checks": self.dependency_checks,
            "environment": self.environment,
            "build": self.build.to_dict() if self.build else None,
            "run": self.run.to_dict() if self.run else None,
            "produced_files": self.produced_files,
        }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build serial NERDSS and run a minimal smoke simulation in an "
            "isolated temporary directory."
        )
    )
    parser.add_argument(
        "--build-system",
        choices=("make", "cmake"),
        default="make",
        help="Serial build backend to use. Default: make.",
    )
    parser.add_argument(
        "--skip-build",
        action="store_true",
        help="Use an existing executable instead of building first.",
    )
    parser.add_argument(
        "--executable",
        type=Path,
        help="NERDSS executable to run. Defaults to the build output.",
    )
    parser.add_argument(
        "--artifact-dir",
        type=Path,
        help=(
            "Directory where the smoke input, command logs, report JSON, and "
            "produced files are preserved. By default the temp directory is "
            "removed after the run."
        ),
    )
    parser.add_argument(
        "--keep-temp",
        action="store_true",
        help="Preserve the temporary smoke run directory.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print the full JSON report to stdout.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=DEFAULT_SEED,
        help=f"Seed passed to NERDSS. Default: {DEFAULT_SEED}.",
    )
    parser.add_argument(
        "--run-timeout",
        type=float,
        default=60.0,
        help="Smoke simulation timeout in seconds. Default: 60.",
    )
    parser.add_argument(
        "--build-timeout",
        type=float,
        default=600.0,
        help="Build timeout in seconds. Default: 600.",
    )
    return parser.parse_args()


def command_to_string(command: Iterable[str]) -> str:
    return " ".join(command)


def output_to_text(output: object) -> str:
    if output is None:
        return ""
    if isinstance(output, bytes):
        return output.decode(errors="replace")
    return str(output)


def run_command(
    command: List[str], cwd: Path, timeout: float, env: Optional[Dict[str, str]] = None
) -> CommandResult:
    started = time.monotonic()
    try:
        completed = subprocess.run(
            command,
            cwd=str(cwd),
            env=env,
            text=True,
            capture_output=True,
            timeout=timeout,
            check=False,
        )
        return CommandResult(
            command=command,
            cwd=str(cwd),
            exit_code=completed.returncode,
            runtime_seconds=time.monotonic() - started,
            stdout=completed.stdout,
            stderr=completed.stderr,
        )
    except subprocess.TimeoutExpired as exc:
        return CommandResult(
            command=command,
            cwd=str(cwd),
            exit_code=None,
            runtime_seconds=time.monotonic() - started,
            stdout=output_to_text(exc.stdout),
            stderr=output_to_text(exc.stderr),
            timed_out=True,
        )


def command_version(command: List[str]) -> Dict[str, object]:
    exe = shutil.which(command[0])
    if exe is None:
        return {"available": False, "path": None, "version": None}

    result = run_command(command, REPO_ROOT, timeout=10.0)
    output = (result.stdout or result.stderr).strip().splitlines()
    return {
        "available": result.ok,
        "path": exe,
        "version": output[0] if output else None,
        "exit_code": result.exit_code,
    }


def collect_environment() -> Dict[str, str]:
    return {
        "python": sys.version.split()[0],
        "platform": platform.platform(),
        "machine": platform.machine(),
    }


def check_dependencies(build_system: str) -> Dict[str, object]:
    checks: Dict[str, object] = {
        "gsl-config": command_version(["gsl-config", "--version"]),
    }
    if build_system == "make":
        checks["make"] = command_version(["make", "--version"])
        checks["g++"] = command_version(["g++", "--version"])
    else:
        checks["cmake"] = command_version(["cmake", "--version"])
    return checks


def missing_dependencies(
    checks: Dict[str, object], build_system: str, skip_build: bool
) -> List[str]:
    if skip_build:
        return []
    required = ["gsl-config"]
    required.append("make" if build_system == "make" else "cmake")
    missing = []
    for name in required:
        info = checks.get(name)
        if not isinstance(info, dict) or not info.get("available"):
            missing.append(name)
    return missing


def build_serial(
    build_system: str, build_timeout: float, report: SmokeReport
) -> Optional[Path]:
    if build_system == "make":
        report.build = run_command(["make", "serial"], REPO_ROOT, build_timeout)
        return REPO_ROOT / "bin" / "nerdss"

    build_dir = REPO_ROOT / "build" / "smoke-serial"
    configure = run_command(
        ["cmake", "-S", str(REPO_ROOT), "-B", str(build_dir), "-DCMAKE_BUILD_TYPE=Release"],
        REPO_ROOT,
        build_timeout,
    )
    if not configure.ok:
        report.build = configure
        return build_dir / "nerdss"

    build = run_command(
        ["cmake", "--build", str(build_dir), "--target", "nerdss"],
        REPO_ROOT,
        build_timeout,
    )
    combined = CommandResult(
        command=[
            "cmake",
            "-S",
            str(REPO_ROOT),
            "-B",
            str(build_dir),
            "&&",
            "cmake",
            "--build",
            str(build_dir),
            "--target",
            "nerdss",
        ],
        cwd=str(REPO_ROOT),
        exit_code=build.exit_code,
        runtime_seconds=configure.runtime_seconds + build.runtime_seconds,
        stdout=configure.stdout + build.stdout,
        stderr=configure.stderr + build.stderr,
        timed_out=configure.timed_out or build.timed_out,
    )
    report.build = combined
    return build_dir / "nerdss"


def stage_smoke_input(smoke_dir: Path) -> Path:
    input_path = smoke_dir / "smoke.inp"
    mol_path = smoke_dir / "A.mol"
    input_path.write_text(SMOKE_INPUT, encoding="utf-8")
    mol_path.write_text(SMOKE_MOL, encoding="utf-8")
    return input_path


def list_produced_files(smoke_dir: Path) -> List[Dict[str, object]]:
    staged_inputs = {"A.mol", "smoke.inp"}
    produced = []
    for path in sorted(smoke_dir.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(smoke_dir).as_posix()
        if rel in staged_inputs:
            continue
        produced.append({"path": rel, "size_bytes": path.stat().st_size})
    return produced


def write_report_artifacts(report: SmokeReport, artifact_dir: Path) -> None:
    artifact_dir.mkdir(parents=True, exist_ok=True)
    report.artifact_dir = str(artifact_dir)
    write_command_logs(report, artifact_dir)
    (artifact_dir / "report.json").write_text(
        json.dumps(report.to_dict(), indent=2) + "\n", encoding="utf-8"
    )


def write_command_logs(report: SmokeReport, artifact_dir: Path) -> None:
    if report.build:
        (artifact_dir / "build.stdout.txt").write_text(report.build.stdout, encoding="utf-8")
        (artifact_dir / "build.stderr.txt").write_text(report.build.stderr, encoding="utf-8")
    if report.run:
        (artifact_dir / "run.stdout.txt").write_text(report.run.stdout, encoding="utf-8")
        (artifact_dir / "run.stderr.txt").write_text(report.run.stderr, encoding="utf-8")


def preserve_artifacts(report: SmokeReport, smoke_dir: Path, artifact_dir: Path) -> None:
    if artifact_dir.exists():
        shutil.rmtree(artifact_dir)
    artifact_dir.mkdir(parents=True)
    output_dir = artifact_dir / "smoke_run"
    shutil.copytree(smoke_dir, output_dir)
    write_report_artifacts(report, artifact_dir)


def print_text_summary(report: SmokeReport) -> None:
    print(f"NERDSS smoke status: {report.status}")
    print(report.message)
    print(f"Build system: {report.build_system}")
    if report.executable:
        print(f"Executable: {report.executable}")
    if report.build:
        print(
            "Build: "
            f"exit={report.build.exit_code} "
            f"runtime={report.build.runtime_seconds:.2f}s "
            f"cmd='{command_to_string(report.build.command)}'"
        )
    if report.run:
        print(
            "Run: "
            f"exit={report.run.exit_code} "
            f"runtime={report.run.runtime_seconds:.2f}s "
            f"cmd='{command_to_string(report.run.command)}'"
        )
    if report.artifact_dir:
        print(f"Artifacts: {report.artifact_dir}")
    print(f"Produced files: {len(report.produced_files)}")
    for item in report.produced_files:
        print(f"  {item['path']} ({item['size_bytes']} bytes)")


def main() -> int:
    args = parse_args()
    report = SmokeReport(
        build_system=args.build_system,
        environment=collect_environment(),
        dependency_checks=check_dependencies(args.build_system),
    )

    missing = missing_dependencies(
        report.dependency_checks, args.build_system, args.skip_build
    )
    if missing:
        report.status = "skipped"
        report.message = (
            "Missing required build dependencies: "
            + ", ".join(missing)
            + ". Install GSL and the selected build tool, then rerun this script."
        )
        if args.artifact_dir:
            write_report_artifacts(report, args.artifact_dir.resolve())
        if args.json:
            print(json.dumps(report.to_dict(), indent=2))
        else:
            print_text_summary(report)
        return 2

    executable = args.executable
    if not args.skip_build:
        executable = build_serial(args.build_system, args.build_timeout, report)
        if report.build and not report.build.ok:
            report.status = "failed"
            report.message = "Serial NERDSS build failed. See captured build stderr/stdout."
            if args.artifact_dir:
                write_report_artifacts(report, args.artifact_dir.resolve())
            if args.json:
                print(json.dumps(report.to_dict(), indent=2))
            else:
                print_text_summary(report)
            return 1

    if executable is None:
        executable = REPO_ROOT / "bin" / "nerdss"
    executable = executable.resolve()
    report.executable = str(executable)
    if not executable.exists():
        report.status = "failed"
        report.message = f"NERDSS executable not found: {executable}"
        if args.artifact_dir:
            write_report_artifacts(report, args.artifact_dir.resolve())
        if args.json:
            print(json.dumps(report.to_dict(), indent=2))
        else:
            print_text_summary(report)
        return 1

    smoke_dir = Path(tempfile.mkdtemp(prefix="nerdss-smoke-"))
    report.smoke_dir = str(smoke_dir)

    try:
        input_path = stage_smoke_input(smoke_dir)
        report.run = run_command(
            [str(executable), "-f", input_path.name, "-s", str(args.seed)],
            smoke_dir,
            args.run_timeout,
        )
        report.produced_files = list_produced_files(smoke_dir)
        if report.run.ok:
            report.status = "passed"
            report.message = "Serial NERDSS build and minimal smoke simulation succeeded."
        elif report.run.timed_out:
            report.status = "failed"
            report.message = f"Smoke simulation timed out after {args.run_timeout:.1f}s."
        else:
            report.status = "failed"
            report.message = "Smoke simulation failed. See captured run stderr/stdout."

        if args.artifact_dir:
            preserve_artifacts(report, smoke_dir, args.artifact_dir.resolve())
        elif args.keep_temp:
            report.artifact_dir = str(smoke_dir)

        if args.json:
            print(json.dumps(report.to_dict(), indent=2))
        else:
            print_text_summary(report)
        return 0 if report.status == "passed" else 1
    finally:
        if not args.keep_temp:
            shutil.rmtree(smoke_dir, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
